export const DEFAULT_EXERCISES = [
  { name: 'Bench Press',            muscle_group: 'chest' },
  { name: 'Incline Bench Press',    muscle_group: 'chest' },
  { name: 'Dumbbell Fly',           muscle_group: 'chest' },
  { name: 'Chest Dip',              muscle_group: 'chest' },
  { name: 'Incline Dumbbell Press', muscle_group: 'chest' },
  { name: 'Squat',                  muscle_group: 'legs' },
  { name: 'Leg Press',              muscle_group: 'legs' },
  { name: 'Romanian Deadlift',      muscle_group: 'legs' },
  { name: 'Leg Curl',               muscle_group: 'legs' },
  { name: 'Leg Extension',          muscle_group: 'legs' },
  { name: 'Calf Raise',             muscle_group: 'legs' },
  { name: 'Hip Thrust',             muscle_group: 'legs' },
  { name: 'Deadlift',               muscle_group: 'back' },
  { name: 'Pull-up',                muscle_group: 'back' },
  { name: 'Lat Pulldown',           muscle_group: 'back' },
  { name: 'Seated Cable Row',       muscle_group: 'back' },
  { name: 'Cable Row',              muscle_group: 'back' },
  { name: 'Barbell Row',            muscle_group: 'back' },
  { name: 'Overhead Press',         muscle_group: 'shoulders' },
  { name: 'Lateral Raise',          muscle_group: 'shoulders' },
  { name: 'Face Pull',              muscle_group: 'shoulders' },
  { name: 'Front Raise',            muscle_group: 'shoulders' },
  { name: 'Shrugs',                 muscle_group: 'shoulders' },
  { name: 'Bicep Curl',             muscle_group: 'arms' },
  { name: 'Hammer Curl',            muscle_group: 'arms' },
  { name: 'Preacher Curl',          muscle_group: 'arms' },
  { name: 'Tricep Pushdown',        muscle_group: 'arms' },
  { name: 'Dips',                   muscle_group: 'arms' },
  { name: 'Skull Crushers',         muscle_group: 'arms' },
  { name: 'Plank',                  muscle_group: 'core' },
]
