export const DEFAULT_EXERCISES = [
  { name: 'Bench Press',            muscle_group: 'chest' },
  { name: 'Incline Bench Press',    muscle_group: 'chest' },
  { name: 'Dumbbell Fly',           muscle_group: 'chest' },
  { name: 'Chest Dip',              muscle_group: 'chest' },
  { name: 'Incline Dumbbell Press', muscle_group: 'chest' },
  { name: 'Squat',                  muscle_group: 'legs' },
  { name: 'Leg Press',              muscle_group: 'legs' },
  { name: 'Romanian Deadlift',      muscle_group: 'legs' },
  { name: 'Leg Curl',               muscle_group: 'legs' },
  { name: 'Leg Extension',          muscle_group: 'legs' },
  { name: 'Calf Raise',             muscle_group: 'legs' },
  { name: 'Hip Thrust',             muscle_group: 'legs' },
  { name: 'Deadlift',               muscle_group: 'back' },
  { name: 'Pull-up',                muscle_group: 'back' },
  { name: 'Lat Pulldown',           muscle_group: 'back' },
  { name: 'Seated Cable Row',       muscle_group: 'back' },
  { name: 'Cable Row',              muscle_group: 'back' },
  { name: 'Barbell Row',            muscle_group: 'back' },
  { name: 'Overhead Press',         muscle_group: 'shoulders' },
  { name: 'Lateral Raise',          muscle_group: 'shoulders' },
  { name: 'Face Pull',              muscle_group: 'shoulders' },
  { name: 'Front Raise',            muscle_group: 'shoulders' },
  { name: 'Shrugs',                 muscle_group: 'shoulders' },
  { name: 'Bicep Curl',             muscle_group: 'arms' },
  { name: 'Hammer Curl',            muscle_group: 'arms' },
  { name: 'Preacher Curl',          muscle_group: 'arms' },
  { name: 'Tricep Pushdown',        muscle_group: 'arms' },
  { name: 'Dips',                   muscle_group: 'arms' },
  { name: 'Skull Crushers',         muscle_group: 'arms' },
  { name: 'Plank',                  muscle_group: 'core' },
  // Additional exercises
  { name: 'Cable Fly',              muscle_group: 'chest' },
  { name: 'Push-up',                muscle_group: 'chest' },
  { name: 'Close-grip Bench Press', muscle_group: 'chest' },
  { name: 'Bulgarian Split Squat',  muscle_group: 'legs' },
  { name: 'Hack Squat',             muscle_group: 'legs' },
  { name: 'Sumo Deadlift',          muscle_group: 'legs' },
  { name: 'Nordic Curl',            muscle_group: 'legs' },
  { name: 'Glute Bridge',           muscle_group: 'legs' },
  { name: 'Seated Calf Raise',      muscle_group: 'legs' },
  { name: 'Step-up',                muscle_group: 'legs' },
  { name: 'Trap Bar Deadlift',      muscle_group: 'back' },
  { name: 'T-Bar Row',              muscle_group: 'back' },
  { name: 'Dumbbell Row',           muscle_group: 'back' },
  { name: 'Chest-Supported Row',    muscle_group: 'back' },
  { name: 'Cable Pullover',         muscle_group: 'back' },
  { name: 'Dumbbell Shoulder Press', muscle_group: 'shoulders' },
  { name: 'Arnold Press',           muscle_group: 'shoulders' },
  { name: 'Upright Row',            muscle_group: 'shoulders' },
  { name: 'Reverse Fly',            muscle_group: 'shoulders' },
  { name: 'Cable Lateral Raise',    muscle_group: 'shoulders' },
  { name: 'EZ Bar Curl',            muscle_group: 'arms' },
  { name: 'Cable Curl',             muscle_group: 'arms' },
  { name: 'Concentration Curl',     muscle_group: 'arms' },
  { name: 'Overhead Tricep Extension', muscle_group: 'arms' },
  { name: 'Cable Tricep Kickback',  muscle_group: 'arms' },
  { name: 'Close-grip Push-up',     muscle_group: 'arms' },
  { name: 'Ab Wheel Rollout',       muscle_group: 'core' },
  { name: 'Hanging Leg Raise',      muscle_group: 'core' },
  { name: 'Cable Crunch',           muscle_group: 'core' },
  { name: 'Russian Twist',          muscle_group: 'core' },
  { name: 'Incline Dumbbell Curl',  muscle_group: 'arms' },
  { name: 'Cable Overhead Extension', muscle_group: 'arms' },
  { name: 'Single-Arm Cable Curl',  muscle_group: 'arms' },
  { name: 'Single-Arm Cable Tricep Extension', muscle_group: 'arms' },
  { name: 'Dumbbell Calf Raise',   muscle_group: 'legs' },
]
